//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessagecontractlcientDemos.CalculatorProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CalculatorProxy.ICalculator")]
    public interface ICalculator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://test/MyMessage_action", ReplyAction="http://test/MyMessage_action")]
        MessagecontractlcientDemos.CalculatorProxy.MyMessage Calculate(MessagecontractlcientDemos.CalculatorProxy.MyMessage request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://test/MyMessage_action", ReplyAction="http://test/MyMessage_action")]
        System.Threading.Tasks.Task<MessagecontractlcientDemos.CalculatorProxy.MyMessage> CalculateAsync(MessagecontractlcientDemos.CalculatorProxy.MyMessage request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MyMessage", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class MyMessage {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string Operation;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public double N1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public double N2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public double Result;
        
        public MyMessage() {
        }
        
        public MyMessage(string Operation, double N1, double N2, double Result) {
            this.Operation = Operation;
            this.N1 = N1;
            this.N2 = N2;
            this.Result = Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalculatorChannel : MessagecontractlcientDemos.CalculatorProxy.ICalculator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculatorClient : System.ServiceModel.ClientBase<MessagecontractlcientDemos.CalculatorProxy.ICalculator>, MessagecontractlcientDemos.CalculatorProxy.ICalculator {
        
        public CalculatorClient() {
        }
        
        public CalculatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MessagecontractlcientDemos.CalculatorProxy.MyMessage MessagecontractlcientDemos.CalculatorProxy.ICalculator.Calculate(MessagecontractlcientDemos.CalculatorProxy.MyMessage request) {
            return base.Channel.Calculate(request);
        }
        
        public void Calculate(ref string Operation, ref double N1, ref double N2, ref double Result) {
            MessagecontractlcientDemos.CalculatorProxy.MyMessage inValue = new MessagecontractlcientDemos.CalculatorProxy.MyMessage();
            inValue.Operation = Operation;
            inValue.N1 = N1;
            inValue.N2 = N2;
            inValue.Result = Result;
            MessagecontractlcientDemos.CalculatorProxy.MyMessage retVal = ((MessagecontractlcientDemos.CalculatorProxy.ICalculator)(this)).Calculate(inValue);
            Operation = retVal.Operation;
            N1 = retVal.N1;
            N2 = retVal.N2;
            Result = retVal.Result;
        }
        
        public System.Threading.Tasks.Task<MessagecontractlcientDemos.CalculatorProxy.MyMessage> CalculateAsync(MessagecontractlcientDemos.CalculatorProxy.MyMessage request) {
            return base.Channel.CalculateAsync(request);
        }
    }
}
